[package]
name = "rublog"
authors = ["Candlest<candlest1112@gmail.com>"]
version = "0.1.1"
edition = "2021"
description = "rublog is a static blog generator written in Rust"
readme = "README.md"
license = "MIT"
keywords = ["static-site-generator"]
repository = "https://github.com/candlest/rublog/"
homepage = "https://github.com/candlest/rublog/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = {version = "1.19.0", features = ["builtins"]}
colored = "2.0.4"
percent-encoding = "2.3.0"
walkdir = "2.3.3"
pulldown-cmark = "0.9.3"
anyhow = "1.0.72"
serde = { version = "1.0.171", features = ["derive"] }
toml = "0.7.6"
clap = { version = "4.3.21", features = ["derive"] }
warp = "0.2.4"
tokio = { version = "0.2.22", features = ["macros"] }
prettytable-rs = "0.10.0"
