[package]
name = "rublog"
authors = ["Candlest<candlest1112@gmail.com>"]
version = "0.1.1"
edition = "2021"
description = "rublog `/rʌblɑg/` is a static blog generator written in `Rust`, still"
readme = "README.md"
license = "MIT"
keywords = ["static-site-generator"]
repository = "https://github.com/candlest/rublog/"
homepage= "https://github.com/candlest/rublog/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
percent-encoding = "2.3.0"
walkdir = "2.3.3"
pulldown-cmark = "0.9.3"
anyhow = "1.0.72"
serde = { version = "1.0.171", features = ["derive"]}
tera = "1.19.0"
toml = "0.7.6"
web_server = "0.4.2"

[package.metadata.rpm]
package = "rublog"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
rublog = { path = "/usr/bin/rublog" }
